[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.tokenizer", "php82Extensions.ctype", "php82Extensions.iconv", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction --no-scripts"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"

